### ISSUE TITLE
CE in MM von einem Contao Artikel rein kopieren geht nicht

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_contentarticle#10]
siehe Issue https://github.com/MetaModels/attribute_translatedcontentarticle/issues/10

**Comment by zonky2** [comment]
verschieben sicher auch nicht...

**Comment by stefanheimes** [comment]
Should be fixed for this repro with the current dev branch. @MacKP if you have the time can you test it please.

**Comment by MacKP** [comment]
@stefanheimes sieht wunderbar aus! Ich liebe es ;-)
