### ISSUE TITLE
Error if User is not Admin -> Table $ptable does not exist

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_contentarticle#13]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_contentarticle/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |      7.4.6    |                                  |
| Contao version:                     |    4.9.22      |                                  |
| MetaModels version:                 |     Version dev-feature/2.2.0     |                                  |
| Installation via composer           | yes |                                  |
| Installed MetaModels packages       |          |                                  |

## Issue description

```
An exception occurred while executing
'SELECT 1 FROM `$ptable` WHERE id='18' LIMIT 0,1':
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'domain-de.$ptable' doesn't exist
```

## Steps to reproduce

Klick on 'Edit' for the Popup

## Describe the behaviour of the application

The Error appears

## Describe the expected behaviour of the application

There should be the Artikel View with everything ;-)

**Comment by discordier** [comment]
https://github.com/MetaModels/attribute_contentarticle/blob/4730ee92d9ead594f24c3594e388f5dc4b6f418a/src/Table/ArticleContent.php#L256
```diff
                 $objContent = Database::getInstance()
-                                      ->prepare('SELECT 1 FROM `$ptable` WHERE id=?')
+                                      ->prepare('SELECT 1 FROM `' . $ptable . '` WHERE id=?')
```

**Comment by MacKP** [comment]
Ich muss noch die aktuelle Version testen und melde mich dazu wieder.. hab anscheinend noch die 2.1er Version...

**Comment by MacKP** [comment]
Zwischeninfo: Patch muss ich noch testen. Auch in der 2.2er Version hab ich noch das Problem.

**Comment by MacKP** [comment]
Aktueller Stand: Bug existiert auch in 2.2@dev und Xtras Lösung funktioniert.

**Comment by MacKP** [comment]
Ach verdammt.. hab nen Patch eingereicht aber Ticket 18 erwähnt... ist aber das Ticket hier -> https://github.com/MetaModels/attribute_contentarticle/pull/14
