### ISSUE TITLE
Using wrong Session Handler

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_contentarticle#6]
See: https://github.com/MetaModels/attribute_contentarticle/blob/27636ebd570d5cc51d3387fa5eb0742e61f30046/src/Table/ArticleContent.php#L130

Instead of using Session Object from Contao we should use this:

https://github.com/MetaModels/attribute_contentarticle/blob/27636ebd570d5cc51d3387fa5eb0742e61f30046/src/Table/ArticleContent.php#L77

The problem is, the the current Id's from the Contao Session Handler aren't the same with the ones of the Container Session handler. So a normal user can't copy any data.

**Comment by zonky2** [comment]
@stefanheimes it´s possible to fix this Issue?
