### ISSUE TITLE
Can't input or Edit Content

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_contentarticle#7]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_contentarticle/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |     7.4     |                                  |
| Contao version:                     |     4.9.14     |  Problem also is in C 4.4.x                                |
| MetaModels version:                 |    latest      |                                  |

## Issue description
When I click on the Edit button the Popup is opened, but there is no Button for new Content-Elements. And also existing Elements are not shown.

I haven't installed the translated Version in this installation of contentarticle.

Kind regards

**Comment by zonky2** [comment]
@MacKP Is the ticket still up to date if Regex is kicked out? see https://github.com/MetaModels/attribute_contentarticle/issues/9

**Comment by MacKP** [comment]
This is a complete different thing.. I don't know the status of this. I think it's a bug without translated and normal contentarticle in the same installation, but I'm not sure at the Moment. Maybe it's fixed, but i have no installation for testing at the Moment.

**Comment by zonky2** [comment]
apparently fixed...
